Create zh_CN file
ArekkuusuJerii/Grimoire-Of-Alice pull request #12
Opened 2017-06-03 07:37 UTC by TartaricAcid

Please do not merge it before @3TUSK approve.

2017-06-03 07:45 UTC, TartaricAcid commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +item.charmofhealing.name=Charm of Healing
The name come from `五つの難題MOD`

2017-06-03 07:45 UTC, TartaricAcid commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +item.nuclearboots.name=核靴子
I don't know how to translate it.

2017-06-03 07:45 UTC, TartaricAcid commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +item.ellyscythe.name=Scythe of the Useless Gatekeeper
Here @3TUSK

2017-06-03 07:45 UTC, TartaricAcid commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +item.crestofyggdrasill.name=Crest Of Yggdrasill
and here

2017-06-03 07:45 UTC, TartaricAcid commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +item.faithitem.name=Faith Item
I don't know how to translate.

2017-06-03 07:45 UTC, TartaricAcid commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +
here

2017-06-03 07:45 UTC, TartaricAcid commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.suwako_hat_header.name="Hoppu hoppu"
here

2017-06-03 07:45 UTC, TartaricAcid commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.mochi_hammer_description_bottom.name=And for all of the 180 children..."
and here

2017-06-03 07:45 UTC, TartaricAcid commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.nazrin_stick_description_header.name=By holding it you become the Little Dowser General
Oh, I forget it

2017-06-03 07:45 UTC, TartaricAcid commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.onbashira_header.name=Leg of an Ent
here

2017-06-03 07:45 UTC, TartaricAcid commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.shichi_seiken_header.name=Gold inlay of clouds and seven stars with the shape of Orsa Mayor
I don't know how to translate `Orsa Mayor`

2017-06-03 07:45 UTC, TartaricAcid commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.sword_of_kusanagi_description_body.name=Discovered within the fourth tail of the eight-headed eight-tailed serpent Yamata-no-Orochi when it was slain by the Shinto god Susanoo-no-Mik
It's diffcult for me.

2017-06-03 07:45 UTC, TartaricAcid commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.roukanken_description_bottom.name=forged by youkai, are close to none!"
and here

2017-06-03 07:45 UTC, TartaricAcid commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.elly_scythe_header.name=War ma fé, heman zo eun Anko drouk
Does it come from Japanese?

2017-06-03 07:45 UTC, TartaricAcid commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.leaf_header.name=Mamisou's Leaf from Ten Desires
here

2017-06-03 07:45 UTC, TartaricAcid commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.uba_mask_vulnerable.name= *Vulnerable to Magic
Tsukumogami of xxx? Vulnerable to xxx?

2017-06-03 09:41 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +item.nuclearboots.name=核靴子
“第三足” - if I read it right

2017-06-03 09:42 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +item.ellyscythe.name=Scythe of the Useless Gatekeeper
[艾丽](https://en.touhouwiki.net/wiki/Elly)的镰刀 / 没用的门卫的镰刀

2017-06-03 09:50 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.sword_of_kusanagi_description_body.name=Discovered within the fourth tail of the eight-headed eight-tailed serpent Yamata-no-Orochi when it was slain by the Shinto god Susanoo-no-Mik
“据信这把剑是须佐之男在杀死八岐大蛇后在它的第四尾中找到的。”

> what the ...

2017-06-03 09:56 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.elly_scythe_header.name=War ma fé, heman zo eun Anko drouk
https://en.wikipedia.org/wiki/Ankou

2017-06-03 10:03 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.roukanken_description_bottom.name=forged by youkai, are close to none!"
对这妖怪锻造的楼观剑来说／斩不断的东西，几乎不存在！

2017-06-03 10:04 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.uba_mask_vulnerable.name= *Vulnerable to Magic
不免疫魔法攻击

2017-06-05 02:10 UTC, 3TUSK requested changes

2017-06-05 02:10 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +item.firerobe.name=火鼠的皮衣
“火鼠之皮衣”，下同

2017-06-05 02:10 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +item.shroompowder.pink.name=粉色蘑菇粉
粉红色

2017-06-05 02:10 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +tile.dragonstone.name=龙之天气石
[龙神石像？](https://thwiki.cc/%E4%B8%9C%E6%96%B9%E6%B1%82%E9%97%BB%E5%8F%B2%E7%BA%AA/%E9%BE%99)

2017-06-05 02:10 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +tile.shroom_6.name=粉色蘑菇
粉红色，下同

2017-06-05 02:10 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.laevatein_header.name=Magic staff gambantein, Lævateinn of fire and chaos
烈火与混沌的魔杖：莱瓦汀

2017-06-05 02:10 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.hisou_sword_description_top.name=拥有一个类似于中国的剑的外观
外观和金色的中国剑相仿

2017-06-05 02:10 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.fox_mask_header.name=Tsukumogami of Determination
[Tsukumogami](https://en.wikipedia.org/wiki/Tsukumogami) -> 付丧神
下同

2017-06-05 02:10 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.mask_of_hope_description.name=Return to Kokoro if found... or not...
捡到后还给秦心...

> include ellipse

2017-06-05 02:11 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.onbashira_header.name=Leg of an Ent
https://en.wikipedia.org/wiki/Ent <- This might help, or not, who knows

2017-06-05 02:11 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.suwako_hat_header.name="Hoppu hoppu"
拟声词

2017-06-05 02:12 UTC, TartaricAcid commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +item.firerobe.name=火鼠的皮衣
我查的中文的THBwiki，火鼠的皮衣

2017-06-05 02:13 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +item.crestofyggdrasill.name=Crest Of Yggdrasill
Potentially something from SAO. Cannot confirm.

2017-06-05 02:18 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +item.faithitem.name=Faith Item
Cherry Item 樱点？
Faith Item 信仰点？
其余待查...

2017-06-05 02:22 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +
Note Shot 音符弹

以及不要只翻译一半....

2017-06-05 05:12 UTC, 3TUSK requested changes

2017-06-05 05:12 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +item.ufos.name=UFOs
去掉s？

2017-06-05 05:12 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +item.danmaku.danmakuvariant.grimoireofalice.leaf.name=叶弹幕
一般是称“xx弹”，而非“xx弹幕”，下同

2017-06-05 05:12 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +achievement.craftBuddhaBowl=新的难题“天竺如来佛的石钵”
新的难题 -> 新难题，下同

2017-06-05 05:12 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.toyosatomimi_hat_description_top.name=我一次可以监听10个人，
我可以同时听十个人说话

2017-06-05 05:12 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.nuclear_boots_description_top.name=左腿“分解之腿”
分解之足 融合之足

2017-06-05 05:12 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.third_eye_header.name=古明地觉的第三只眼
原文没有“古明地” (Komeiji)

2017-06-05 05:12 UTC, 3TUSK commented on src/main/resources/assets/grimoireofalice/lang/zh_CN.lang
> +grimoire.tooltip.fuku_no_kami_mask_header.name=付丧神的幽默
"A of B" -> “B的A”，下同

2017-06-05 05:28 UTC, 3TUSK approved these changes

2017-06-05 14:38 UTC, TartaricAcid commented
@ArekkuusuJerii I think the PR can be merge.

2017-06-05 14:48 UTC, merged